# Ex02

### Given qubit and two gates test-commit with message bla bla

In [3]:
import numpy as np

In [4]:
vector = [1,2]

gate1 = [[1,0],[0,1]]

gate2 = [[1,1],[1,1]]

### Calculation of dot products

In [5]:
vect1 = np.dot(vector,gate1)
print(vect1)
vect2 = np.dot(vect1,gate2)
print(vect2)

[1 2]
[3 3]


### Kronecker product of gate1 and gate2

In [6]:
print(np.kron(gate1,gate2))

[[1 1 0 0]
 [1 1 0 0]
 [0 0 1 1]
 [0 0 1 1]]


### We can also do this with the Hadamard gate which maps the {|0>,|1>} basis to the {|+>,|->} basis and vice versa (see bloch sphere)

In [17]:
vect1 = [1,0]
Hadamard = [[1,1],[1,-1]]*1/np.sqrt(2)

np.dot(vect1,Hadamard)

array([0.70710678, 0.70710678])

### Say we have an output state [2,2], we determine the probability of measuring this output given the input vector

In [8]:
psi1=[2,2]
print(np.dot(vector,psi1)**2)

36
