# Ex02

### Given qubit and two gates

In [2]:
import numpy as np

In [3]:
vector = [1,2]

gate1 = [[1,0],[0,1]]

gate2 = [[1,1],[1,1]]

### Calculation of dot products

In [4]:
vect1 = np.dot(vector,gate1)
print(vect1)
vect2 = np.dot(vect1,gate2)
print(vect2)

[1 2]
[3 3]


### Kronecker product of gate1 and gate2

In [5]:
print(np.kron(gate1,gate2))

[[1 1 0 0]
 [1 1 0 0]
 [0 0 1 1]
 [0 0 1 1]]


### Say we have an output state [2,2], we determine the probability of measuring this output given the input vector

In [6]:
psi1=[2,2]
print(np.dot(vector,psi1)**2)

36
