# Ex02

### Given qubit and two gates test-commit

In [24]:
import numpy as np
import math as mt

In [10]:
vector = [1/3,2/3]

gate1 = [[1,0],[0,1]]

gate2 = [[1,1],[1,1]]

### Calculation of dot products

In [11]:
vect1 = np.dot(vector,gate1)
print(vect1)
vect2 = np.dot(vect1,gate2)
print(vect2)

[0.33333333 0.66666667]
[1. 1.]


### Kronecker product of gate1 and gate2

In [12]:
print(np.kron(gate1,gate2))

[[1 1 0 0]
 [1 1 0 0]
 [0 0 1 1]
 [0 0 1 1]]


### Say we have a normalized output state [1/2,1/2], we determine the probability of measuring this output given the input vector

In [13]:
psi1=[1/2,1/2]
print(np.dot(vector,psi1)**2)

0.25


### Below we use the Hadamard gate which transform vector space {|0>,|1>} to vector space {|+>,|->}

In [66]:
H = [[1/mt.sqrt(2),1/mt.sqrt(2)],[1/mt.sqrt(2),-1/mt.sqrt(2)]]

In [27]:
np.dot(H,[1,0])

array([0.70710678, 0.70710678])

### Circuit of two qubits applying CNOT-gate

#### First we initialize two states, both |1>

In [36]:
psi1 = [0,1]
psi2 = [0,1]

comb = np.kron(psi1,psi2)

print(comb)

[0 0 0 1]


In [37]:
CNOT = [[1,0,0,0],[0,1,0,0],[0,0,0,1],[0,0,1,0]]
comb_CNOT = np.dot(CNOT,comb)

print(comb_CNOT)

[0 0 1 0]


#### We see that the state is flipped from [0,0,0,1] (|1> ⊗ |1>) to [0,0,1,0] (|1> ⊗ |0>). This is the exact function of the CNOT-gate; it flips the second qubit (if and only if the first qubit is |1>) and retains the first qubit

#### Say we do this circuit and want to measure the probability of measuring |1>⊗|1>; or a random state (of same length)

In [55]:
np.dot(comb,comb_CNOT)**2

0

In [56]:
rng = np.random.default_rng()
rndom = rng.choice(5, 4)/5
print(rndom)
print(np.dot(rndom,comb_CNOT))

[0.6 0.2 0.2 0.8]
0.2


### Bell Basis

In [62]:
phiplus = [i*1/2 for i in [1,0,0,1]]
phiminus = [i*1/2 for i in [1,0,0,-1]]
psiplus = [i*1/2 for i in [0,1,1,0]]
psiminus = [i*1/2 for i in [0,1,-1,0]]

## Test

In [67]:
class Gatedict:
    Hadamard = np.array([[1/mt.sqrt(2),1/mt.sqrt(2)],[1/mt.sqrt(2),-1/mt.sqrt(2)]])
    CNOT = np.array([[1,0,0,0],[0,1,0,0],[0,0,0,1],[0,0,1,0]])

print(Gatedict.Hadamard)

[[ 0.70710678  0.70710678]
 [ 0.70710678 -0.70710678]]


In [6]:
import math as mt
import numpy as np
A = np.array([2,3])
print(A)
print(np.dot([[1,1],[1,1]],A))

[2 3]
[5 5]


In [13]:
import qutip as qt
import matplotlib.pyplot as plt
import numpy as np

state = qt.core.states.basis(2)

xvec = np.linspace(-5,5,200)

W_fock = qt.wigner(state)

plt.plot(xvec,W_fock)
plt.show()

TypeError: wigner() missing 1 required positional argument: 'xvec'