# 100 numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel
free to open an issue at <https://github.com/rougier/numpy-100>.

File automatically generated. See the documentation to update questions/answers/hints programmatically.

Run the `initialize.py` module, then for each question you can query the
answer or an hint with `hint(n)` or `answer(n)` for `n` question number.

In [1]:
%run initialise.py

#### 1. Import the numpy package under the name `np` (★☆☆)

In [17]:
import numpy as np
from sys import getsizeof

#### 2. Print the numpy version and the configuration (★☆☆)

In [8]:
np.version.version

'1.26.4'

#### 3. Create a null vector of size 10 (★☆☆)

In [14]:
A = np.zeros(10)
print(A)
print(len(A))

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
10


#### 4. How to find the memory size of any array (★☆☆)

In [18]:
getsizeof(A)

192

#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [20]:
help(np.add)

Help on ufunc:

add = <ufunc 'add'>
    add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

    Add arguments element-wise.

    Parameters
    ----------
    x1, x2 : array_like
        The arrays to be added.
        If ``x1.shape != x2.shape``, they must be broadcastable to a common
        shape (which becomes the shape of the output).
    out : ndarray, None, or tuple of ndarray and None, optional
        A location into which the result is stored. If provided, it must have
        a shape that the inputs broadcast to. If not provided or None,
        a freshly-allocated array is returned. A tuple (possible only as a
        keyword argument) must have length equal to the number of outputs.
    where : array_like, optional
        This condition is broadcast over the input. At locations where the
        condition is True, the `out` array will be set to the ufunc result.
        Elsewhere, the `out` array will retai

#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [22]:
A[4] = 1
print(A)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [24]:
B = np.arange(10,50)
print(B)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [25]:
print(np.flip(B))

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [29]:
print(np.arange(0,9).reshape(3,3))

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [36]:
np.argwhere(np.asarray([1,2,0,0,4,0])>0)

array([[0],
       [1],
       [4]], dtype=int64)

#### 11. Create a 3x3 identity matrix (★☆☆)

In [44]:
C = np.zeros(9)
print(C)
C[0]=1
C[4]=1
C[8]=1
print(C.reshape(3,3))

[0. 0. 0. 0. 0. 0. 0. 0. 0.]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 12. Create a 3x3x3 array with random values (★☆☆)

In [46]:
print(np.random.rand(3,3,3))

[[[0.23971785 0.77458541 0.28392575]
  [0.7446127  0.38531341 0.30757497]
  [0.26219634 0.18667609 0.49984285]]

 [[0.88117984 0.52769414 0.28222527]
  [0.331091   0.9207052  0.3907752 ]
  [0.58367771 0.39939826 0.66154124]]

 [[0.62785244 0.96765218 0.09473425]
  [0.05107684 0.49709228 0.56335579]
  [0.60619454 0.4573809  0.6859115 ]]]


#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [51]:
D = np.random.rand(10,10)
print(D)
print(np.min(D))
print(np.max(D))

[[0.76926421 0.4900887  0.36790201 0.51194955 0.81235839 0.11028728
  0.83228431 0.72534301 0.18869269 0.74391429]
 [0.38555805 0.40983424 0.13155172 0.66573145 0.11489205 0.18110748
  0.8918312  0.0491914  0.09863389 0.59034562]
 [0.97712608 0.26399124 0.07527986 0.40385897 0.64325622 0.85531603
  0.60324927 0.46679835 0.43101303 0.09870656]
 [0.97919584 0.46631782 0.56899784 0.372871   0.50437011 0.30674382
  0.4557481  0.19694783 0.10000399 0.48542802]
 [0.85774499 0.4855675  0.11572223 0.79256487 0.27380133 0.13034127
  0.0028095  0.39636438 0.76958533 0.43625656]
 [0.6758529  0.25606505 0.35659775 0.74463359 0.29802605 0.34470644
  0.64061757 0.18093309 0.97076767 0.92382497]
 [0.66078867 0.49040436 0.06302149 0.3381987  0.95940733 0.55102472
  0.57268995 0.97030669 0.61493037 0.45705552]
 [0.61757198 0.04094608 0.29861647 0.38913547 0.87830029 0.06520289
  0.8545536  0.03511938 0.57841471 0.01782579]
 [0.56485063 0.38262421 0.50778121 0.69939109 0.81509661 0.4808812
  0.23762563 

#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [56]:
E = np.random.rand(30)
print(E)
print(np.mean(E))

[0.34578317 0.82300773 0.22555801 0.42053143 0.31544401 0.42014664
 0.99905324 0.43865505 0.93005629 0.28579424 0.69298968 0.44227187
 0.04108644 0.61495833 0.29717503 0.52797461 0.90999888 0.32640636
 0.65445088 0.94975472 0.43670951 0.26923117 0.18111987 0.25721646
 0.99809308 0.35427815 0.784697   0.56323857 0.89372811 0.28676959]
0.5228726038709387


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [64]:
F = np.ones(9).reshape(3,3)
F[1:-1,1:-1]=0
print(F)

[[1. 1. 1.]
 [1. 0. 1.]
 [1. 1. 1.]]


#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [70]:
F = np.ones(9).reshape(3,3)
F[:,[0,-1]]=F[[0,-1],:]=0
print(F)

[[0. 0. 0.]
 [0. 1. 0.]
 [0. 0. 0.]]


#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [80]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.3 == 3 * 0.1)

nan
False
False
nan
True
False


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [84]:
G = np.zeros(25).reshape(5,5)
G[1,0]=1
G[2,1]=2
G[3,2]=3
G[4,3]=4
print(G)

[[0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 2. 0. 0. 0.]
 [0. 0. 3. 0. 0.]
 [0. 0. 0. 4. 0.]]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [100]:
G = np.zeros(64)
G = G.reshape(8,8)
for i in range(8):
    if i%2==0:
        G[i,::2]=1
    else:
        G[i,1::2]=1
print(G)

[[1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)

In [112]:
print(np.unravel_index(99,(6,7,8)))

(1, 5, 3)


#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [119]:
print(np.array([[0,1],[1,0]]))
Z = np.tile( np.array([[0,1],[1,0]]), (4,4))
print(Z)

[[0 1]
 [1 0]]
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 22. Normalize a 5x5 random matrix (★☆☆)

In [130]:
def normalize_array(arr):
    norm_arr = (arr - np.min(arr)) / (np.max(arr) - np.min(arr))
    return norm_arr

L = np.random.rand(5,5)*5.3
L = L.flatten()
print(normalize_array(L))

[0.843877   0.76194029 0.         0.57492515 0.99017547 1.
 0.178083   0.03726382 0.14474766 0.03110081 0.76148113 0.33843105
 0.00670929 0.10721299 0.10174117 0.62636731 0.17887947 0.88911704
 0.84854004 0.94736548 0.4359354  0.27929181 0.23496488 0.66292174
 0.82795056]


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [133]:
color = np.dtype([("r", np.ubyte),
                  ("g", np.ubyte),
                  ("b", np.ubyte),
                  ("a", np.ubyte)])

print(color)

[('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')]


#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [137]:
M = np.random.rand(5,3)
N = np.random.rand(3,2)
print(np.dot(M,N))
print(M @ N)

[[0.18459505 0.51867166]
 [0.92219522 1.31693125]
 [0.55711454 0.99066952]
 [0.35729055 0.96980479]
 [0.33412998 0.51497636]]
[[0.18459505 0.51867166]
 [0.92219522 1.31693125]
 [0.55711454 0.99066952]
 [0.35729055 0.96980479]
 [0.33412998 0.51497636]]


#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [144]:
O = np.random.rand(10)*10
print(O)
print((O<8) & (O>3))

[8.05663035 9.17731026 4.57796332 2.72591045 4.81367543 9.74902933
 4.28054372 6.00945928 1.89734216 7.92508999]
[False False  True False  True False  True  True False  True]


#### 26. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

#### 28. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

#### 29. How to round away from zero a float array ? (★☆☆)

#### 30. How to find common values between two arrays? (★☆☆)

#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

#### 40. Create a random vector of size 10 and sort it (★★☆)

#### 41. How to sum a small array faster than np.sum? (★★☆)

#### 42. Consider two random array A and B, check if they are equal (★★☆)

#### 43. Make an array immutable (read-only) (★★☆)

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)

#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) (★★☆)

#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)

#### 49. How to print all the values of an array? (★★☆)

#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

#### 54. How to read the following file? (★★☆)
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

#### 56. Generate a generic 2D Gaussian-like array (★★☆)

#### 57. How to randomly place p elements in a 2D array? (★★☆)

#### 58. Subtract the mean of each row of a matrix (★★☆)

#### 59. How to sort an array by the nth column? (★★☆)

#### 60. How to tell if a given 2D array has null columns? (★★☆)

#### 61. Find the nearest value from a given value in an array (★★☆)

#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

#### 63. Create an array class that has a name attribute (★★☆)

#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★☆)

#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

#### 69. How to get the diagonal of a dot product? (★★★)

#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

#### 72. How to swap two rows of an array? (★★★)

#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

#### 74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

#### 75. How to compute averages using a sliding window over an array? (★★★)

#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

#### 82. Compute a matrix rank (★★★)

#### 83. How to find the most frequent value in an array?

#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)

#### 86. Consider a set of p matrices with shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

#### 89. How to get the n largest values of an array (★★★)

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

#### 91. How to create a record array from a regular array? (★★★)

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

#### 95. Convert a vector of ints into a matrix binary representation (★★★)

#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)